### ISSUE TITLE
AMD Radeon RX 9060 XT (16GB) gfx1200 doesn't work with zluda

### ISSUE THREAD

**Issue by Nem404** [lshqqytiger/ZLUDA#116]
I get this error everytime:

"rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.2\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1200
rocBLAS error: Could not initialize Tensile host:
regex_error(error_backref): The expression contained an invalid back reference."

Isn't there a workaround or smth?

**Comment by CS1o** [comment]
Hey you need the additional GFX files for your GPU. You find them here: (You need the .zip for GFX1200)
Currently they are missing, but they should get added in the upcoming days.
https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4

Also here is an install Guide:
https://github.com/CS1o/Stable-Diffusion-Info/wiki/Webui-Installation-Guides#amd-automatic1111-with-zluda

**Comment by Nem404** [comment]
Thx man, I somehow made it work on Windows by experimenting with wsl2 ubuntu and rocm, then copying the opt\rocm-6.4.1\lib\rocblas\library (Linux) folder to AMD\ROCm\6.2\bin\rocblas\library (Windows) folder, but this way the performance is really lackluster. I've tried every single optimization but cant get more that 3,5 - 4 s/it which is not good. Directml gives around the same. I think zluda can't use well the rdna4 architecture yet. We need a patch or update or so for the gfx1200, gfx1201 and for the other yet unreleased rdna4 cards...

**Comment by lshqqytiger** [comment]
It is not because zluda doesn't support RDNA 4, but HIP SDK 6.2 does not.
The currently available rocBLAS tensile logics are fallback ones, and not optimized for gfx120x, so the performance is bad.

**Comment by 1635200412** [comment]
> I get this error everytime:
> 
> "rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.2\bin/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1200 rocBLAS error: Could not initialize Tensile host: regex_error(error_backref): The expression contained an invalid back reference."
> 
> Isn't there a workaround or smth?

Do not use the amdhip64_6.dll from ROCm HIP. Instead, use the one that comes with the driver. As for how to call it, simply place it in the directory of the ZLUDA dll, and that can be done.

**Comment by Nem404** [comment]
> It is not because zluda doesn't support RDNA 4, but HIP SDK 6.2 does not. The currently available rocBLAS tensile logics are fallback ones, and not optimized for gfx120x, so the performance is bad.

I see. Theoretically could there be any improvements or we need to wait for like Q4 2025 till AMD does smth with that famous rocm windows pytorch support? For rdna4 I mean

**Comment by Nem404** [comment]
> > I get this error everytime:
> > "rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.2\bin/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1200 rocBLAS error: Could not initialize Tensile host: regex_error(error_backref): The expression contained an invalid back reference."
> > Isn't there a workaround or smth?
> 
> Do not use the amdhip64_6.dll from ROCm HIP. Instead, use the one that comes with the driver. As for how to call it, simply place it in the directory of the ZLUDA dll, and that can be done.

Have you actually tried this? Does this help with the generation speed by any chance?

**Comment by 1635200412** [comment]
> > > I get this error everytime:
> > > "rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.2\bin/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1200 rocBLAS error: Could not initialize Tensile host: regex_error(error_backref): The expression contained an invalid back reference."
> > > Isn't there a workaround or smth?
> > 
> > 
> > Do not use the amdhip64_6.dll from ROCm HIP. Instead, use the one that comes with the driver. As for how to call it, simply place it in the directory of the ZLUDA dll, and that can be done.
> 
> Have you actually tried this? Does this help with the generation speed by any chance?

I misspoke - you should delete the amdhip dll in the ROCm installation directory, and it will automatically locate the corresponding file in the driver

**Comment by LiVeenMusic** [comment]
Psst, figured I should mention that June 19th, the custom libraries for GFX1200 became available at https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4 
Very possible you guys knew that and are already talking about it, but didn't seem clear to me, so figured I'd be the guy that mentions it. It's "unoptimized" though, but hey, I guess it's better than nothing!

If anyone ever builds Hipblaslt for gfx1031 on windows, btw, please lemme know, I've been trying for months now, but my system is apparently borked enough these days that I can't get it to successfully build no matter what I try.

**Comment by Nem404** [comment]
> Psst, figured I should mention that June 19th, the custom libraries for GFX1200 became available at https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4 Very possible you guys knew that and are already talking about it, but didn't seem clear to me, so figured I'd be the guy that mentions it. It's "unoptimized" though, but hey, I guess it's better than nothing!
> 
> If anyone ever builds Hipblaslt for gfx1031 on windows, btw, please lemme know, I've been trying for months now, but my system is apparently borked enough these days that I can't get it to successfully build no matter what I try.

Yes bro I told likelovewant to put the libraries of gfx1200 too in his repo. But the unoptimized logics are not that good, based my own testing they are like quarter the performance of the same workload under my wls2 linux subsystem where rocm 6.4.1 natively supports and has optimized logics for the gfx1200

**Comment by Nem404** [comment]
@lshqqytiger Can you pls add RDNA4 support to your TheRock PyTorch release, right now there isn't a normal logical way for me to use my gfx1200 on Windows, pytorch wheels for it would be amazing. Thx in advance

**Comment by alshdavid** [comment]
FWIW, rdna4 cards perform poorly natively under Linux and ROCm too. I get approximately the same performance under Windows/Zluda as I do Linux/ROCm (~3% slower) so it's not likely to be an issue with the ROCmLibs or Zluda.

ROCm 7 comes out soon (an RC1 branch was just created on the ROCm repo, so it's probably not long now). Not sure what improvement we will see for 9000 series cards, but here's hoping but they are currently unusable for AI workloads at the moment.

- https://github.com/ROCm/ROCm/issues/4846
- https://github.com/ROCm/ROCm/issues/5040

**Comment by benlann** [comment]
I told a 9060xt user to try this guide:
https://github.com/patientx/ComfyUI-Zluda/issues/222
Along with using the 6.5 hip development sdk:
https://drive.google.com/file/d/124N7C22-tiC8XR-QmPDqvmfSrF6LRglh/view?usp=sharing
He reported that it fixed his problems, now he is faster or rather as slow as the rest of us

**Comment by sfinktah** [comment]
Wouldn't the HIP 6.5 SDK (url as listed by @benlann) cause Triton to compile more efficient code for the existing hip drivers in `c:\windows\system32\amdhip64_6.dll` which are actually for HIP 6.4?  I don't know if you SDNext people actually put drivers in your ZLUDA directory or even use Triton, but I have no issues doing what I just described.

I also don't have a RDNA4 card, so I can't report on how well it works.

@alshdavid Have you tried using the rocm/pytorch-nightly docker build?  That ships with pytorch 7 and (IIRC) rocm 6.4.

**Comment by Nem404** [comment]
Zluda doesn't work at all with greater hip sdk/rocm versions than 6.2, because there are breaking api changes between 6.2 and >6.3

**Comment by Nem404** [comment]
Closing this issue (as not planned) because the only solution for this would be rocm 7 with native pytorch on Windows (so without zluda). Which isn't that far I think

**Comment by sfinktah** [comment]
@Nem404

> Zluda doesn't work at all with greater hip sdk/rocm versions than 6.2, because there are breaking api changes between 6.2 and >6.3

Think about what you're saying.  Look at the properties of `c:\windows\system32\amdhip64_6.dll` and observe that it is version 6.4.  If there are breaking changes, and you're compiling with version 6.2, don't you think it would have broken by now?

Unless you guys are doing something crazy like copying the old 6.2 DLLs from the `ROCm/HIP/6.2` directory to your working paths so that they are preferentially loaded, you'll find that you are using the DLLs from `windows/system32` -- you can check with many windows tools which DLL is running.

Even if you have contrived to load the ancient amdhip64 DLL that comes with the SDK, we at patientx's ComfyUI+ZLUDA definately don't, and I can assure you that we would have noticed it breaking by now, given that 6.4 DLL has been shipping in the Adrenaline drivers for quite a long time now.

To be fair, I **have** noticed intermittent issues with 6.5 and compiling the VAE for Flux, but absolutely 0 issues with WAN.  I've also had no issues with SD, SDXL and its variants, though I don't use torch.compile on those.  As Flux shares the same VAE as SD3, there could possibly be issues I simply haven't encountered because I don't compile SD-ish models -- mainly because I'm not sure how that would work with checkpoints.   More that willing to try though.

**Comment by Nem404** [comment]
@sfinktah show me the hip sdk 6.4 installer for Windows. I dont care about that specific dll file. Hip sdk as a whole.

**Comment by sfinktah** [comment]
I wish I could, I wish I had it or knew where to get it.  It would make a whole lot more sense to be able to compile with the same version as the DLL we are linking too, since we are losing all the features that are available.

That AMD haven't bothered to release a 6.4 SDK simply confirms that there cannot really be a breaking difference between 6.2 and 6.3 (or 6.4).

**Comment by Nem404** [comment]
@lshqqytiger himself said this to my bro on Discord:
"there are breaking api changes between 6.2 and >6.3"
If you dont believe me, we can ask him.

**Comment by sfinktah** [comment]
Empirical evidence beats known fact every time.

It works.  If prefer to take someone's word over actually testing it yourself, that's your privilege as one of this repos authors.

**Comment by Nem404** [comment]
Yeah so you know it better than the man who made using zluda with pytorch possible even after vosen rolled back their original zluda

**Comment by lshqqytiger** [comment]
I don't remember what the breaking api changes were, but it is fact that there are breaking api changes between the official build of HIP SDK 6.2 and my local build of HIP SDK develop branch. (for example, in rocBLAS, gemm_ex3 / gemm_ex_64)
But it seems also true that my ZLUDA branch can be compiled and run with 6.3, 6.4, or 6.5. (I haven't thoroughly tested with those versions enough)

**Comment by sfinktah** [comment]
Oh, there are definately some issues with using the 6.5 SDK against the 6.4 HIP DLL that is installed in `system32` by Adrenaline, but I've only noticed them when compiling Flux models and VAE, and they are not usually fatal.

Given @Nem404's issues are related to his gfx1200, and gfx1200 support was (I believe) added in version 6.4.0, it seemed a solution worth pursuing.

Unless you happen to know where these mysterious SDK leaks originate? 

I think I will probably buy a gfx1200 for myself when I can afford it, seems like an inexpensive secondary GPU.

Oh, and @Nem404, I'm a guy that actually got Lee's Triton to work with torch.inductor compilation even though pytorch 2.7 doesn't support version of Triton higher that 3.0, and I'm also a guy who used to write cheats for GTA 5 -- which quite similar to zluda, in that it involves a lot of DLL hooking, memory manipulation, on-the-fly code manipulation, and basically tricking the system into believing lies.  I believe the [New York Times](https://www.nytimes.com/2018/11/07/world/australia/grand-theft-auto-cheat-mods-melbourne.html) wrote a piece about me.

**Comment by Nem404** [comment]
@sfinktah youre amazing

**Comment by alshdavid** [comment]
> [@alshdavid](https://github.com/alshdavid) Have you tried using the rocm/pytorch-nightly docker build? That ships with pytorch 7 and (IIRC) rocm 6.4.

@sfinktah  Trying to get it working now;

- ComfyUI starts but crashes before it can generate an image
- SDNext doesn't start but in the debug output reports ROCm 6.4

```bash
docker run --net=host -v $HOME:/home/root:Z --privileged -it --rm rocm/pytorch-nightly /bin/bash

apt install rocminfo radeontop nano

# reports device correctly
radeontop 

# both report rocm 6.4.1
update-alternatives --display rocm
ls -l -a /opt | grep rocm
>  rocm-6.4.1/

python --version 
> 3.10.18

python -c "import torch; print(torch.__version__)"
> 2.9.0a0+git4167311

cd /home/root
git clone https://github.com/comfyanonymous/ComfyUI.git

# comment out 
# torch
# torchvision
# torchaudio
nano ./requirements.txt

# Conflicts
pip uninstall numba
pip uninstall numpy

pip install -r ./requirements.txt

# launches, server is available, fails when generating
python ./main.py
```

**Comment by sfinktah** [comment]
@alshdavid well that sucks.  it does crash randomly for me, but it's not common (and I don't really use it much anyway -- way too slow), and I also only have a gfx1100.

do you have gfx1201 or a gfx1200?  and when you say "perform poorly" do you mean: "slower than a gfx1100" or just "not as fast as it says on the packet"?

**Comment by alshdavid** [comment]
I have a gfx1201 (9070xt) and it takes about twice as long to complete a generative task compared to my old 6900xt. I have numbers here: https://github.com/ROCm/ROCm/issues/4846#issue-3102786947

I'm now trying to install ROCm 7 on Fedora directly via the RHL beta repositories - will let you know if that makes a difference.

I've been renting cloud GPUs to tie me over 🙄 Such a joke

EDIT: Ok, it appears that running ROCm 7 beta on Fedora 42 directly performs about the same as ROCm 6.4

**Comment by sfinktah** [comment]
> EDIT: Ok, it appears that running ROCm 7 beta on Fedora 42 directly performs about the same as ROCm 6.4

@alshdavid I'm not sure if that's a good thing, an adequate thing, or simply not a terribly bad thing.   I confess I thought you had a gfx1200, as I didn't think the situation could be that bad for gfx1201. I wonder how bad a https://frame.work/au/en/desktop would be?

@lshqqytiger They officially released ROCm 6.4 HIP SDK for Windows sometime last week when I wasn't looking: https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-25.Q3-Win10-Win11-For-HIP.exe

It does unfortunately break ZLUDA's `cudnn64_9.dll` shim and probably the rest of them.

**Comment by Nem404** [comment]
@sfinktah not sure if you’re interested, but Lee has made a HIP SDK 6.4 zluda patch over at the sdnext repo: https://github.com/vladmandic/sdnext/commit/83be0d77d7db5979ad1bb14d22950b5d92088edd
It’s just not in https://github.com/lshqqytiger/ZLUDA yet.

**Comment by sfinktah** [comment]
@Nem404 Oh wow, thanks.  I actually built ZLUDA myself, but naturally it didn't work any better just because I built it.  And it took me ages.  Hours of my life I will never get back.  _quietly glares at lee_.  `set RUSTFLAGS=-C link-args=Advapi32.lib`  

Aha! I see now, thanks Nem404.  You forced me to run a dependency walk, which showed me that miopen.dll was missing, which reminded me that AMD releases crappy SDKs, so I will copy the 6.4 SDK over the 6.5 SDK and call it a day.

**Comment by lshqqytiger** [comment]
I'm planning to release HIP SDK extension that contains customized MIOpen with next version of ZLUDA. cudnn.dll will be available after that.

**Comment by Nem404** [comment]
> I'm planning to release HIP SDK extension that contains customized MIOpen with next version of ZLUDA. cudnn.dll will be available after that.

Great news!
