### ISSUE TITLE
PyTorch 2.6.0 (ZLUDA nightly 3.9.5) CUBLAS_STATUS_NOT_SUPPORTED on AMD Radeon 780M

### ISSUE THREAD

**Issue by Ardssass** [lshqqytiger/ZLUDA#118]
**Environment:**
- **ZLUDA Version**: ZLUDA-nightly-windows-rocm6-amd64 v3.9.5
- **Operating System**: Windows 11
- **Python Version**: 3.12.9
- **PyTorch Version**: 2.6.0+cu118
- **ROCm Version**: 6.2
- **GPU**: AMD Radeon 780M Graphics
- **AMD Software**: PRO Edition 25.Q2

- I have installed the full contents of the HIP SDK 6.2.4 on Windows 11.
- I also replaced `rocblas.dll` and other library files from `rocm.gfx1103.AMD.780M.phoenix.V5.0.for.hip.sdk.6.2.4.7z`.
- I merged the HIP SDK extension into `C:\ROCm\6.2`.
- Replaced the following DLL files in my PyTorch installation:
  - `cufft64_10.dll`
  - `cufftw64_10.dll`
  - `cusparse64_11.dll`
  - `nvrtc64_112_0.dll`
  - `cublas64_11.dll`
  - `cudnn64_9.dll`

**Description:**
I am encountering a persistent `CUBLAS_STATUS_NOT_SUPPORTED` error when running a PyTorch test script using ZLUDA. The error occurs during the `torch.nn.Linear` forward pass, which calls `cublasLtMatmulAlgoGetHeuristic`.

This issue happens consistently in every training batch, for both FP32 and AMP (Automatic Mixed Precision) modes. The script is designed to be very stable, using `BatchNorm`, gradient clipping, and a dataset free of `NaN`/`inf` values, but the error still occurs immediately at the first matrix multiplication operation.

**Steps to Reproduce:**

```python
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# 1. Environment Check
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")
    print(f"cuDNN version: {torch.backends.cudnn.version()}")
    print(f"Current device: {torch.cuda.get_device_name(torch.cuda.current_device())}")


# 2. Set Device
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# 3. Custom Safe Dataset (to prevent NaN generation)
class SafeDataset(Dataset):
    def __init__(self, num_samples=1000, input_dim=10):
        # Generate safe random data
        self.data = torch.randn(num_samples, input_dim) * 0.1  # Reduce numerical range for stability
        self.labels = torch.randint(0, 2, (num_samples,)).float()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

# 4. Simple Neural Network (with BatchNorm for stability)
class SafeModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 128)
        self.bn1 = nn.BatchNorm1d(128)
        self.fc2 = nn.Linear(128, 64)
        self.bn2 = nn.BatchNorm1d(64)
        self.fc3 = nn.Linear(64, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.bn2(x)
        x = self.relu(x)
        x = self.fc3(x)
        return self.sigmoid(x)

# 5. Check for NaN/inf in data
def check_data_for_nan(data_loader):
    for i, (inputs, labels) in enumerate(data_loader):
        if torch.isnan(inputs).any() or torch.isinf(inputs).any():
            print(f"⚠️ NaN/inf found in input of batch {i}: {inputs}")
            return True
        if torch.isnan(labels).any() or torch.isinf(labels).any():
            print(f"⚠️ NaN/inf found in labels of batch {i}: {labels}")
            return True
    return False

# 6. Training diagnostics function
def safe_diagnostics(loss, inputs=None, outputs=None, labels=None):
    if torch.isnan(loss) or torch.isinf(loss):
        print(f"❌ Abnormal loss - NaN: {torch.isnan(loss)}, Inf: {torch.isinf(loss)}")
        return True
    return False

# 7. Main training function
def train_model_safe(use_amp=True, lr=0.01, clip_grad=False, max_norm=1.0, bf16=False):
    torch.manual_seed(42)

    dataset = SafeDataset(num_samples=1000, input_dim=10)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)
    model = SafeModel(input_dim=10).to(device)
    criterion = nn.BCELoss()
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)

    # AMP settings
    dtype = torch.bfloat16 if bf16 else torch.float16
    # Use the new recommended API for GradScaler and autocast
    scaler = torch.amp.GradScaler('cuda', enabled=use_amp and torch.cuda.is_available())

    # Check for initial data issues
    print("\nChecking for NaN/Inf in training data...")
    if check_data_for_nan(dataloader):
        print("Critical Error: NaN/Inf detected in dataset, terminating training!")
        return
    else:
        print("✅ Data check passed, no NaN/Inf found.")

    # Training loop
    num_epochs = 3
    is_bf16 = bf16 and torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    print(f"\nStarting training (AMP={use_amp}{', BF16' if is_bf16 else ''}, LR={lr})...")

    for epoch in range(num_epochs):
        print(f"\n{'='*40} Epoch {epoch+1}/{num_epochs} {'='*40}")
        model.train()

        for batch_idx, (inputs, labels) in enumerate(dataloader):
            inputs, labels = inputs.to(device), labels.to(device)

            try:
                optimizer.zero_grad()

                with torch.amp.autocast(device_type='cuda', dtype=dtype, enabled=use_amp and torch.cuda.is_available()):
                    outputs = model(inputs)
                    loss = criterion(outputs.squeeze(), labels)

                if safe_diagnostics(loss):
                    print("⛔️ Numerical instability detected, skipping this batch.")
                    continue

                if use_amp and torch.cuda.is_available():
                    scaler.scale(loss).backward()
                    if clip_grad:
                        scaler.unscale_(optimizer)
                        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm)
                    scaler.step(optimizer)
                    scaler.update()
                else: # FP32 training
                    loss.backward()
                    if clip_grad:
                        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm)
                    optimizer.step()

                if batch_idx % 10 == 0:
                    print(f"Batch [{batch_idx}/{len(dataloader)}] - Loss: {loss.item():.6f}")

            except Exception as e:
                print(f"\n❌ Batch {batch_idx} failed: {e}")
                print(f"  Input shape: {inputs.shape}, dtype: {inputs.dtype}")
                print(f"  Label shape: {labels.shape}, dtype: {labels.dtype}")
                # Stop on first error to provide a clean traceback
                print("\nAborting training due to error.")
                return

    print("✅ Training finished!")
    print("="*60)


if __name__ == "__main__":
    if not torch.cuda.is_available():
        print("CUDA not available. Exiting.")
    else:
        # Test Case 1: FP32 training as baseline
        print("\n⭐️ Test Case 1: Safe training without AMP (FP32)")
        train_model_safe(use_amp=False, lr=0.01, clip_grad=True, max_norm=1.0)
```

**Observed Behavior (Console Output):**
This is the output when running the script above. The error occurs immediately in the first test case (FP32).

```
PyTorch version: 2.6.0+cu118
CUDA available: True
CUDA version: 11.8
cuDNN version: 90100
Current device: AMD Radeon RX 7800M
Using device: cuda:0

⭐️ Test Case 1: Safe training without AMP (FP32)

Checking for NaN/Inf in training data...
✅ Data check passed, no NaN/Inf found.

Starting training (AMP=False, LR=0.01)...

======================================== Epoch 1/3 ========================================

❌ Batch 0 failed: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`
  Input shape: torch.Size([32, 10]), dtype: torch.float32
  Label shape: torch.Size([32]), dtype: torch.float32

Aborting training due to error.
Traceback (most recent call last):
  File "AMP_test.py", line 186, in <module>
    train_model_safe(use_amp=False, lr=0.01, clip_grad=True, max_norm=1.0)
  File "AMP_test.py", line 155, in train_model_safe
    loss.backward()
  File "...\torch\tensor.py", line 715, in backward
    torch.autograd.backward(
  File "...\torch\autograd\__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into C++
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`

```
Thank you for your time and assistance.

**Comment by lshqqytiger** [comment]
> If you have PyTorch version >2.4 and are not using nightly build, set the following environment variable.
> ```
> DISABLE_ADDMM_CUDA_LT=1
> ```
Instead, you can use nightly build after installing extension. (not recommended)

https://github.com/lshqqytiger/ZLUDA?tab=readme-ov-file#pytorch

**Comment by Ardssass** [comment]
I have already set this environment variable to `1` in my environment. I've verified its setting, and it appears correctly as shown in the attached image snippet :



![Image](https://github.com/user-attachments/assets/8169e84b-cb26-417a-a28e-f4b60b16b24d)



However, despite setting this variable, I am still encountering the exact same error:

```
❌ Batch 0 failed: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`
  Input shape: torch.Size([32, 10]), dtype: torch.float32
  Label shape: torch.Size([32]), dtype: torch.float32

Aborting training due to error.
```

**Crucially, I want to add that this issue was *not present before* recent updates to my system.** The error began occurring specifically after I upgraded the following components:

*   **AMD Software**: Upgraded from PRO Edition 24.20.52 to 25.Q2.
*   **ZLUDA**: Upgraded from ZLUDA-nightly-windows-rocm6-amd64 v3.9.4 to ZLUDA-nightly-windows-rocm6-amd64 v3.9.5.

This suggests a potential regression or incompatibility introduced with these newer versions of the AMD driver or ZLUDA.

Given this new information, could you please provide further guidance? Perhaps there's a known incompatibility with these specific driver/ZLUDA versions, or another workaround that might be applicable.

**Comment by Ardssass** [comment]
After clearing ZLUDA's cache and rerunning it, the error is gone. Thanks for your help.
