### ISSUE TITLE
Why doesn't cuDNN work?

### ISSUE THREAD

**Issue by ComradePenguin-1917** [lshqqytiger/ZLUDA#81]
I paste all files in HIP-SDK-extension.zip to C:\Program Files\AMD\ROCm\6.2 following the guide and I use the following code to test the installation of cuDNN:
```
import torch
import torch.nn as nn

device = torch.device('cuda:0')
print(f"CUDA available on {torch.cuda.get_device_name(device)}")

print(f"PyTorch Version: {torch.__version__}")
print(f"CUDA Version: {torch.version.cuda}")
print(f"cuDNN Enabled: {torch.backends.cudnn.enabled}")
print(f"cuDNN Version: {torch.backends.cudnn.version()}")

try:
    x = torch.randn(1, 1, 4, 4, device=device)
    conv = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=0).to(device)
    output = conv(x)
    print(f"Input size: {x.shape} → output size: {output.shape}")

except Exception as e:
    print(f"{str(e)}")
```
I get this output:
```
CUDA available on AMD Radeon RX 6800 [ZLUDA]
PyTorch Version: 2.3.1+cu118
CUDA Version: 11.8
cuDNN Enabled: True
cuDNN Version: 8700
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```
Why?

**Comment by ComradePenguin-1917** [comment]
Well, this time, the output becomes:
```
CUDA available on AMD Radeon RX 6800 [ZLUDA]
PyTorch Version: 2.6.0+cu118
CUDA Version: 11.8
cuDNN Enabled: True
cuDNN Version: 90100
MIOpen Error: E:/ML/MIOpen/src/include\miopen/sqlite_db.hpp:252: Cannot open database file:C:\Users\XXXX\.miopen\cache\3.4.0.15a37b44f\gfx1030_30.ukdb
thread '<unnamed>' panicked at zluda_dnn\src\lib.rs:70:16:
[ZLUDA] MIOpen failed: 5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core\src\panicking.rs:223:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7ffb35471fc1 - cudnnConvolutionBackwardData
   1:     0x7ffb3547efba - cudnnConvolutionBackwardData
   2:     0x7ffb354707a7 - cudnnConvolutionBackwardData
   3:     0x7ffb35471e05 - cudnnConvolutionBackwardData
   4:     0x7ffb354733a5 - cudnnConvolutionBackwardData
   5:     0x7ffb35473184 - cudnnConvolutionBackwardData
   6:     0x7ffb35473a33 - cudnnConvolutionBackwardData
   7:     0x7ffb35473882 - cudnnConvolutionBackwardData
   8:     0x7ffb3547270f - cudnnConvolutionBackwardData
   9:     0x7ffb354734be - cudnnConvolutionBackwardData
  10:     0x7ffb35487d25 - cudnnConvolutionBackwardData
  11:     0x7ffb35487dd3 - cudnnConvolutionBackwardData
  12:     0x7ffb35487eb5 - cudnnConvolutionBackwardData
  13:     0x7ffb3546c963 - cudnnBackendFinalize
  14:     0x7ffb8028f730 - _CxxFrameHandler3
  15:     0x7ffb802833d8 - is_exception_typeof
  16:     0x7ffb877c3886 - RtlCaptureContext2
  17:     0x7ffb3546c947 - cudnnBackendFinalize
  18:     0x7ff99747f98c - at::native::cudnn_convolution_transpose
  19:     0x7ff997482e71 - at::native::cudnn_convolution_transpose
  20:     0x7ff99748bfa7 - at::native::cudnn_convolution_transpose
  21:     0x7ff997492237 - at::native::cudnn_convolution_transpose
  22:     0x7ff9974905bb - at::native::cudnn_convolution_transpose
  23:     0x7ff99745df3b - at::native::cudnn_convolution_add_relu
  24:     0x7ff99745c88b - at::native::cudnn_convolution
  25:     0x7ff99910e2d4 - at::cuda::where_outf
  26:     0x7ff999034cea - at::cuda::bucketize_outf
  27:     0x7ff98cc88e96 - at::_ops::vsplit_int::redispatch
  28:     0x7ff98cd06677 - at::_ops::cudnn_convolution::call
  29:     0x7ff98c228124 - at::native::_convolution
  30:     0x7ff98d13d0dd - at::compositeexplicitautograd::view_copy_symint_outf
  31:     0x7ff98d10bcde - at::compositeexplicitautograd::bucketize_outf
  32:     0x7ff98c7f6214 - at::TensorMaker::make_tensor
  33:     0x7ff98c89df8e - at::_ops::_convolution::call
  34:     0x7ff98c2273bb - at::native::sym_size
  35:     0x7ff98c23376b - at::native::convolution
  36:     0x7ff98d13efe3 - at::compositeexplicitautograd::view_copy_symint_outf
  37:     0x7ff98d10bdef - at::compositeexplicitautograd::bucketize_outf
  38:     0x7ff98c7f60b0 - at::TensorMaker::make_tensor
  39:     0x7ff98c87dbec - at::TensorMaker::make_tensor
  40:     0x7ff98c95578c - at::_ops::convolution::redispatch
  41:     0x7ff98e406774 - torch::autograd::GraphRoot::apply
  42:     0x7ff98e3fcb75 - torch::autograd::GraphRoot::apply
  43:     0x7ff98c7f60b0 - at::TensorMaker::make_tensor
  44:     0x7ff98c8cc999 - at::_ops::convolution::call
  45:     0x7ff98c23211d - at::native::conv2d_symint
  46:     0x7ff98d2d1098 - at::compositeimplicitautograd::where
  47:     0x7ff98d2b45b0 - at::compositeimplicitautograd::broadcast_to_symint
  48:     0x7ff98c7f5e8b - at::TensorMaker::make_tensor
  49:     0x7ff98ce13bf7 - at::_ops::conv2d::call
  50:     0x7ff9855089f9 - THPPointer<_frame>::release
  51:     0x7ff98555dd35 - THPPointer<_frame>::release
  52:     0x7ffb1d55140d - cfunction_call
                               at \Objects\methodobject.c:543
  53:     0x7ffb1d50c2a8 - _PyObject_MakeTpCall
                               at \Objects\call.c:215
  54:     0x7ffb1d620e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  55:     0x7ffb1d620e02 - call_function
                               at \Python\ceval.c:5893
  56:     0x7ffb1d61d14d - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4181
  57:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  58:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  59:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  60:     0x7ffb1d50e941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  61:     0x7ffb1d50eaed - method_vectorcall
                               at \Objects\classobject.c:53
  62:     0x7ffb1d618891 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  63:     0x7ffb1d620e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  64:     0x7ffb1d620e02 - call_function
                               at \Python\ceval.c:5893
  65:     0x7ffb1d61d14d - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4181
  66:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  67:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  68:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  69:     0x7ffb1d50e941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  70:     0x7ffb1d50eb8a - method_vectorcall
                               at \Objects\classobject.c:83
  71:     0x7ffb1d621002 - PyObject_Call
                               at \Objects\call.c:317
  72:     0x7ffb1d621002 - do_call_core
                               at \Python\ceval.c:5945
  73:     0x7ffb1d61bf60 - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4277
  74:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  75:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  76:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  77:     0x7ffb1d50e941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  78:     0x7ffb1d50eb8a - method_vectorcall
                               at \Objects\classobject.c:83
  79:     0x7ffb1d621002 - PyObject_Call
                               at \Objects\call.c:317
  80:     0x7ffb1d621002 - do_call_core
                               at \Python\ceval.c:5945
  81:     0x7ffb1d61bf60 - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4277
  82:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  83:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  84:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  85:     0x7ffb1d50c0b4 - _PyObject_FastCallDictTstate
                               at \Objects\call.c:142
  86:     0x7ffb1d50c8d2 - _PyObject_Call_Prepend
                               at \Objects\call.c:431
  87:     0x7ffb1d57a0f4 - slot_tp_call
                               at \Objects\typeobject.c:7494
  88:     0x7ffb1d50c2a8 - _PyObject_MakeTpCall
                               at \Objects\call.c:215
  89:     0x7ffb1d620e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  90:     0x7ffb1d620e02 - call_function
                               at \Python\ceval.c:5893
  91:     0x7ffb1d61cbbd - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4213
  92:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  93:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  94:     0x7ffb1d692661 - PyEval_EvalCode
                               at \Python\ceval.c:1134
  95:     0x7ffb1d692661 - run_eval_code_obj
                               at \Python\pythonrun.c:1291
  96:     0x7ffb1d692748 - run_mod
                               at \Python\pythonrun.c:1312
  97:     0x7ffb1d692348 - pyrun_file
                               at \Python\pythonrun.c:1208
  98:     0x7ffb1d69016b - _PyRun_SimpleFileObject
                               at \Python\pythonrun.c:456
  99:     0x7ffb1d48baba - _PyRun_AnyFileObject
                               at \Python\pythonrun.c:90
 100:     0x7ffb1d48baba - pymain_run_file_obj
                               at \Modules\main.c:357
 101:     0x7ffb1d48c731 - pymain_run_file
                               at \Modules\main.c:376
 102:     0x7ffb1d48c731 - pymain_run_python
                               at \Modules\main.c:595
 103:     0x7ffb1d48d483 - Py_RunMain
                               at \Modules\main.c:674
 104:     0x7ffb1d48d483 - pymain_main
                               at \Modules\main.c:1070
 105:     0x7ffb1d48d4f6 - Py_Main
                               at \Modules\main.c:1082
 106:     0x7ff6f9841490 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
 107:     0x7ff6f9841490 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
 108:     0x7ffb8659e8d7 - BaseThreadInitThunk
 109:     0x7ffb8775bf2c - RtlUserThreadStart
thread caused non-unwinding panic. aborting.
```

**Comment by ComradePenguin-1917** [comment]
> Please install PyTorch 2.6.0 and copy cudnn.dll over torch/lib/cudnn64_9.dll. Also, set environment variable `DISABLE_ADDMM_CUDA_LT=1`.

Well, this time the output becomes:
```
CUDA available on AMD Radeon RX 6800 [ZLUDA]
PyTorch Version: 2.6.0+cu118
CUDA Version: 11.8
cuDNN Enabled: True
cuDNN Version: 90100
MIOpen Error: E:/ML/MIOpen/src/include\miopen/sqlite_db.hpp:252: Cannot open database file:C:\Users\谈峻杉\.miopen\cache\3.4.0.15a37b44f\gfx1030_30.ukdb
thread '<unnamed>' panicked at zluda_dnn\src\lib.rs:70:16:
[ZLUDA] MIOpen failed: 5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core\src\panicking.rs:223:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7ffb35471fc1 - cudnnConvolutionBackwardData
   1:     0x7ffb3547efba - cudnnConvolutionBackwardData
   2:     0x7ffb354707a7 - cudnnConvolutionBackwardData
   3:     0x7ffb35471e05 - cudnnConvolutionBackwardData
   4:     0x7ffb354733a5 - cudnnConvolutionBackwardData
   5:     0x7ffb35473184 - cudnnConvolutionBackwardData
   6:     0x7ffb35473a33 - cudnnConvolutionBackwardData
   7:     0x7ffb35473882 - cudnnConvolutionBackwardData
   8:     0x7ffb3547270f - cudnnConvolutionBackwardData
   9:     0x7ffb354734be - cudnnConvolutionBackwardData
  10:     0x7ffb35487d25 - cudnnConvolutionBackwardData
  11:     0x7ffb35487dd3 - cudnnConvolutionBackwardData
  12:     0x7ffb35487eb5 - cudnnConvolutionBackwardData
  13:     0x7ffb3546c963 - cudnnBackendFinalize
  14:     0x7ffb8028f730 - _CxxFrameHandler3
  15:     0x7ffb802833d8 - is_exception_typeof
  16:     0x7ffb877c3886 - RtlCaptureContext2
  17:     0x7ffb3546c947 - cudnnBackendFinalize
  18:     0x7ff99747f98c - at::native::cudnn_convolution_transpose
  19:     0x7ff997482e71 - at::native::cudnn_convolution_transpose
  20:     0x7ff99748bfa7 - at::native::cudnn_convolution_transpose
  21:     0x7ff997492237 - at::native::cudnn_convolution_transpose
  22:     0x7ff9974905bb - at::native::cudnn_convolution_transpose
  23:     0x7ff99745df3b - at::native::cudnn_convolution_add_relu
  24:     0x7ff99745c88b - at::native::cudnn_convolution
  25:     0x7ff99910e2d4 - at::cuda::where_outf
  26:     0x7ff999034cea - at::cuda::bucketize_outf
  27:     0x7ff98cc88e96 - at::_ops::vsplit_int::redispatch
  28:     0x7ff98cd06677 - at::_ops::cudnn_convolution::call
  29:     0x7ff98c228124 - at::native::_convolution
  30:     0x7ff98d13d0dd - at::compositeexplicitautograd::view_copy_symint_outf
  31:     0x7ff98d10bcde - at::compositeexplicitautograd::bucketize_outf
  32:     0x7ff98c7f6214 - at::TensorMaker::make_tensor
  33:     0x7ff98c89df8e - at::_ops::_convolution::call
  34:     0x7ff98c2273bb - at::native::sym_size
  35:     0x7ff98c23376b - at::native::convolution
  36:     0x7ff98d13efe3 - at::compositeexplicitautograd::view_copy_symint_outf
  37:     0x7ff98d10bdef - at::compositeexplicitautograd::bucketize_outf
  38:     0x7ff98c7f60b0 - at::TensorMaker::make_tensor
  39:     0x7ff98c87dbec - at::TensorMaker::make_tensor
  40:     0x7ff98c95578c - at::_ops::convolution::redispatch
  41:     0x7ff98e406774 - torch::autograd::GraphRoot::apply
  42:     0x7ff98e3fcb75 - torch::autograd::GraphRoot::apply
  43:     0x7ff98c7f60b0 - at::TensorMaker::make_tensor
  44:     0x7ff98c8cc999 - at::_ops::convolution::call
  45:     0x7ff98c23211d - at::native::conv2d_symint
  46:     0x7ff98d2d1098 - at::compositeimplicitautograd::where
  47:     0x7ff98d2b45b0 - at::compositeimplicitautograd::broadcast_to_symint
  48:     0x7ff98c7f5e8b - at::TensorMaker::make_tensor
  49:     0x7ff98ce13bf7 - at::_ops::conv2d::call
  50:     0x7ff9855089f9 - THPPointer<_frame>::release
  51:     0x7ff98555dd35 - THPPointer<_frame>::release
  52:     0x7ffb1d55140d - cfunction_call
                               at \Objects\methodobject.c:543
  53:     0x7ffb1d50c2a8 - _PyObject_MakeTpCall
                               at \Objects\call.c:215
  54:     0x7ffb1d620e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  55:     0x7ffb1d620e02 - call_function
                               at \Python\ceval.c:5893
  56:     0x7ffb1d61d14d - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4181
  57:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  58:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  59:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  60:     0x7ffb1d50e941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  61:     0x7ffb1d50eaed - method_vectorcall
                               at \Objects\classobject.c:53
  62:     0x7ffb1d618891 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  63:     0x7ffb1d620e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  64:     0x7ffb1d620e02 - call_function
                               at \Python\ceval.c:5893
  65:     0x7ffb1d61d14d - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4181
  66:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  67:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  68:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  69:     0x7ffb1d50e941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  70:     0x7ffb1d50eb8a - method_vectorcall
                               at \Objects\classobject.c:83
  71:     0x7ffb1d621002 - PyObject_Call
                               at \Objects\call.c:317
  72:     0x7ffb1d621002 - do_call_core
                               at \Python\ceval.c:5945
  73:     0x7ffb1d61bf60 - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4277
  74:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  75:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  76:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  77:     0x7ffb1d50e941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  78:     0x7ffb1d50eb8a - method_vectorcall
                               at \Objects\classobject.c:83
  79:     0x7ffb1d621002 - PyObject_Call
                               at \Objects\call.c:317
  80:     0x7ffb1d621002 - do_call_core
                               at \Python\ceval.c:5945
  81:     0x7ffb1d61bf60 - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4277
  82:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  83:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  84:     0x7ffb1d50c65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  85:     0x7ffb1d50c0b4 - _PyObject_FastCallDictTstate
                               at \Objects\call.c:142
  86:     0x7ffb1d50c8d2 - _PyObject_Call_Prepend
                               at \Objects\call.c:431
  87:     0x7ffb1d57a0f4 - slot_tp_call
                               at \Objects\typeobject.c:7494
  88:     0x7ffb1d50c2a8 - _PyObject_MakeTpCall
                               at \Objects\call.c:215
  89:     0x7ffb1d620e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  90:     0x7ffb1d620e02 - call_function
                               at \Python\ceval.c:5893
  91:     0x7ffb1d61cbbd - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4213
  92:     0x7ffb1d61f4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  93:     0x7ffb1d61f4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  94:     0x7ffb1d692661 - PyEval_EvalCode
                               at \Python\ceval.c:1134
  95:     0x7ffb1d692661 - run_eval_code_obj
                               at \Python\pythonrun.c:1291
  96:     0x7ffb1d692748 - run_mod
                               at \Python\pythonrun.c:1312
  97:     0x7ffb1d692348 - pyrun_file
                               at \Python\pythonrun.c:1208
  98:     0x7ffb1d69016b - _PyRun_SimpleFileObject
                               at \Python\pythonrun.c:456
  99:     0x7ffb1d48baba - _PyRun_AnyFileObject
                               at \Python\pythonrun.c:90
 100:     0x7ffb1d48baba - pymain_run_file_obj
                               at \Modules\main.c:357
 101:     0x7ffb1d48c731 - pymain_run_file
                               at \Modules\main.c:376
 102:     0x7ffb1d48c731 - pymain_run_python
                               at \Modules\main.c:595
 103:     0x7ffb1d48d483 - Py_RunMain
                               at \Modules\main.c:674
 104:     0x7ffb1d48d483 - pymain_main
                               at \Modules\main.c:1070
 105:     0x7ffb1d48d4f6 - Py_Main
                               at \Modules\main.c:1082
 106:     0x7ff6f9841490 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
 107:     0x7ff6f9841490 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
 108:     0x7ffb8659e8d7 - BaseThreadInitThunk
 109:     0x7ffb8775bf2c - RtlUserThreadStart
thread caused non-unwinding panic. aborting.
```

**Comment by ComradePenguin-1917** [comment]
I tried to search the file gfx1030_30.ukdb from C:\Users\XXXX\.miopen\cache\3.4.0.15a37b44f but there dosen't exist such file. Did I do something wrong?

**Comment by ComradePenguin-1917** [comment]
Also I unpack the 'ZLUDA-nightly-windows-rocm6-amd64.zip' and add it to the environment variable.

**Comment by lshqqytiger** [comment]
I can't reproduce your error.
I got not implemented error when cuStreamGetPriority was called, but not MIOpen error.
After implementing get priority function, it works fine.
Could you try again with `MIOPEN_LOG_LEVEL=6`? https://rocm.docs.amd.com/projects/MIOpen/en/latest/how-to/debug-log.html

![Image](https://github.com/user-attachments/assets/fead503b-ebb3-454e-883d-7b32a470425c)

**Comment by ComradePenguin-1917** [comment]
> I can't reproduce your error. I got not implemented error when cuStreamGetPriority was called, but not MIOpen error. After implementing get priority function, it works fine. Could you try again with `MIOPEN_LOG_LEVEL=6`? https://rocm.docs.amd.com/projects/MIOpen/en/latest/how-to/debug-log.html
> 
> ![Image](https://github.com/user-attachments/assets/fead503b-ebb3-454e-883d-7b32a470425c)

```
CUDA available on AMD Radeon RX 6800 [ZLUDA]
PyTorch Version: 2.6.0+cu118
CUDA Version: 11.8
cuDNN Enabled: True
cuDNN Version: 90100
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
MIOpen(HIP): Info [Handle] stream: 0000000000000000, device_id: 0
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
MIOpen(HIP): Info [SetStream] stream: 0000000000000000, device_id: 0
MIOpen(HIP): Info2 [isIsomorphic] test failed due to num nodes being different
MIOpen(HIP): Info2 [isIsomorphic] test failed due to num nodes being different
MIOpen(HIP): Info2 [isIsomorphic] test failed due to num nodes being different
MIOpen(HIP): Info2 [isIsomorphic] test failed due to num nodes being different
MIOpen(HIP): Info2 [findEngines] Matched against pattern: convolution_fwd
MIOpen(HIP): Info [] MIOPEN_FIND_MODE = DYNAMIC_HYBRID(5)
MIOpen(HIP): Info2 [default_allocator] GetAvailableMemory 16967991296
MIOpen(HIP): Info2 [default_allocator] hipMalloc 64 at 0000000400004000 Ok
MIOpen(HIP): Info2 [default_allocator] GetAvailableMemory 16967991296
MIOpen(HIP): Info2 [default_allocator] hipMalloc 36 at 0000000400005000 Ok
MIOpen(HIP): Info2 [default_allocator] GetAvailableMemory 16967991296
MIOpen(HIP): Info2 [default_allocator] hipMalloc 16 at 0000000400006000 Ok
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 6.2.41512, MIOpen version 3.4.0.15a37b44f
MIOpen(HIP): Info2 [GetWorkSpaceSize]
MIOpen(HIP): Info [GetSolutions]
MIOpen(HIP): Info2 [GetInstalledPathFile] inexact find database search
MIOpen(HIP): Info [GetInstalledPathFile] Database directory does not exist
MIOpen(HIP): Info [Measure] ReadonlyRamDb::Prefetch time: 0 ms
MIOpen(HIP): Info [Measure] RamDb::Prefetch time: 0.1692 ms
MIOpen(HIP): Info2 [ValidateUnsafe] DB file is newer than cache: 226781870800, 87918910600
MIOpen(HIP): Info2 [FindRecord] RamDb file is newer than cache, prefetching
MIOpen(HIP): Info [Measure] RamDb::Prefetch time: 0.0526 ms
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F in cache for file "C:\\Users\\****\\.miopen\\db\\gfx1030_30.HIP.3_4_0_c83c11bfb.ufdb.txt"
MIOpen(HIP): Info2 [FindRecord] Looking for key 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F in file ""
MIOpen(HIP): Info2 [Measure] Db::FindRecord time: 0.8976 ms
MIOpen(HIP): Info2 [GetSolutionsFallback] [Warning] Caught exception: (E:/ML/MIOpen/src/conv/heuristics/ai_heuristics.cpp:39: Unable to load file: gfx908_metadata.tn.model), passing empty solver vector
MIOpen(HIP): Info2 [GetSolutionsFallback] Using WTI Fallback
MIOpen(HIP): Info2 [GetSolutionsFallback] ConvDirectNaiveConvFwd Estimated WTI = 0.01
MIOpen(HIP): Info2 [GetSolutionsFallback] GemmFwdRest Estimated WTI = 0.36
MIOpen(HIP): Info2 [GetSolutionsFallback] maxSolutionCount = 1, available = 2
MIOpen(HIP): Info2 [GetSolutionsFallback] id: 85, algo: 1, time: 1000, ws: 0, name: ConvDirectNaiveConvFwd
MIOpen(HIP): Info2 [GetSolutionsFallback] id: 91, algo: 0, time: 27.7778, ws: 144, name: GemmFwdRest
MIOpen(HIP): Info2 [GetWorkspaceSizes] fft: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmFwd1x1_0_1: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmFwd1x1_0_1_int8: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmFwd1x1_0_2: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmFwdRest: 144
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmBwd1x1_stride1: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmBwd1x1_stride2: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmBwdRest: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmWrw1x1_stride1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] GemmWrwUniversal: Not applicable
MIOpen(HIP): Info2 [GetMaxWorkSpaceSize] 0 < 144
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsm3x3U: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsm1x1U: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsm1x1UV2: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsm5x10u2v2f1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsm7x7c3h224w224k64u2v2p3q3f1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsm5x10u2v2b1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvOclDirectFwd11x11: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvOclDirectFwdGen: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvOclDirectFwd1x1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvOclDirectFwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvDirectNaiveConvFwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvDirectNaiveConvBwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvDirectNaiveConvWrw: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmForwardV4R5Xdlops: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmForwardV4R4Xdlops: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmBwdDataV4R1Xdlops: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmBwdDataV1R1Xdlops: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmV4R1Fwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmV4R4Fwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMlirIgemmFwdXdlops: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMlirIgemmFwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMlirIgemmBwdXdlops: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMlirIgemmBwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmBwdDataV1R1: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvHipImplicitGemmBwdDataV4R1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmV4R1DynamicFwd_1x1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmV4R1DynamicFwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmV4R1DynamicBwd: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmGTCDynamicFwdXdlops: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmGTCDynamicBwdXdlops: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvCkIgemmFwdV6r1DlopsNchw: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvBinWinograd3x3U: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvBinWinogradRxSf3x2: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvBinWinogradRxSf2x3: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvBinWinogradRxSf2x3g1: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvBinWinogradRxS: Skipped (no workspace required)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd<3-3>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd<4-3>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd<5-3>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd<6-3>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd_xdlops<2-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd_xdlops<3-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd_xdlops<4-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd_xdlops<5-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvMPBidirectWinograd_xdlops<6-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [GetWorkspaceSizes] ConvWinoFuryRxS<2-3>: Not applicable
MIOpen(HIP): Info [GetWorkSpaceSize] 144
MIOpen(HIP): Info2 [default_allocator] GetAvailableMemory 16967991296
MIOpen(HIP): Info2 [default_allocator] hipMalloc 144 at 0000000400007000 Ok
MIOpen(HIP): Info [GetSolutions]
MIOpen(HIP): Info2 [ValidateUnsafe] DB file is newer than cache: 226781870800, 87919638100
MIOpen(HIP): Info2 [FindRecord] RamDb file is newer than cache, prefetching
MIOpen(HIP): Info [Measure] RamDb::Prefetch time: 0.0247 ms
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F in cache for file "C:\\Users\\****\\.miopen\\db\\gfx1030_30.HIP.3_4_0_c83c11bfb.ufdb.txt"
MIOpen(HIP): Info2 [FindRecord] Looking for key 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F in file ""
MIOpen(HIP): Info2 [Measure] Db::FindRecord time: 0.2576 ms
MIOpen(HIP): Info2 [GetSolutionsFallback] [Warning] Caught exception: (E:/ML/MIOpen/src/conv/heuristics/ai_heuristics.cpp:39: Unable to load file: gfx908_metadata.tn.model), passing empty solver vector
MIOpen(HIP): Info2 [GetSolutionsFallback] Using WTI Fallback
MIOpen(HIP): Info2 [GetSolutionsFallback] ConvDirectNaiveConvFwd Estimated WTI = 0.01
MIOpen(HIP): Info2 [GetSolutionsFallback] GemmFwdRest Estimated WTI = 0.36
MIOpen(HIP): Info2 [GetSolutionsFallback] maxSolutionCount = 1, available = 2
MIOpen(HIP): Info2 [GetSolutionsFallback] id: 85, algo: 1, time: 1000, ws: 0, name: ConvDirectNaiveConvFwd
MIOpen(HIP): Info2 [GetSolutionsFallback] id: 91, algo: 0, time: 27.7778, ws: 144, name: GemmFwdRest
MIOpen(HIP): Info2 [ValidateUnsafe] DB file is newer than cache: 226781870800, 87946252300
MIOpen(HIP): Info2 [FindRecord] RamDb file is newer than cache, prefetching
MIOpen(HIP): Info [Measure] RamDb::Prefetch time: 0.0222 ms
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F in cache for file "C:\\Users\\****\\.miopen\\db\\gfx1030_30.HIP.3_4_0_c83c11bfb.ufdb.txt"
MIOpen(HIP): Info2 [Measure] Db::FindRecord time: 0.1952 ms
MIOpen(HIP): Info [TryLoad] Find-db regenerating.
MIOpen(HIP): Info2 [Find] Starting find for miopenConvolutionFwdAlgoWinograd
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvBinWinograd3x3U: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvBinWinogradRxSf3x2: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvBinWinogradRxSf2x3: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvBinWinogradRxSf2x3g1: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvBinWinogradRxS: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd<3-3>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd<4-3>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd<5-3>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd<6-3>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd_xdlops<2-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd_xdlops<3-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd_xdlops<4-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd_xdlops<5-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMPBidirectWinograd_xdlops<6-3>: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinoFuryRxS<2-3>: Not applicable
MIOpen(HIP): Info2 [Find] Starting find for miopenConvolutionFwdAlgoDirect
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsm3x3U: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsm1x1U: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsm1x1UV2: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsm5x10u2v2f1: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsm7x7c3h224w224k64u2v2p3q3f1: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsm5x10u2v2b1: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvOclDirectFwd11x11: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvOclDirectFwdGen: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvOclDirectFwd1x1: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvOclDirectFwd: Skipped (non-dynamic)
MIOpen(HIP): Info [FindSolutionImpl] ConvDirectNaiveConvFwd (not searchable)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvDirectNaiveConvFwd: Success.
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvDirectNaiveConvBwd: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvDirectNaiveConvWrw: Not applicable
MIOpen(HIP): Info2 [Find] Starting find for miopenConvolutionFwdAlgoImplicitGEMM
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmForwardV4R5Xdlops: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmForwardV4R4Xdlops: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmBwdDataV4R1Xdlops: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmBwdDataV1R1Xdlops: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmV4R1Fwd: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmV4R4Fwd: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMlirIgemmFwdXdlops: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMlirIgemmFwd: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMlirIgemmBwdXdlops: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvMlirIgemmBwd: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmBwdDataV1R1: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmBwdDataV4R1: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmV4R1DynamicFwd_1x1: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmV4R1DynamicFwd: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmV4R1DynamicBwd: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmGTCDynamicFwdXdlops: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmGTCDynamicBwdXdlops: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvCkIgemmFwdV6r1DlopsNchw: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC: Not applicable
MIOpen(HIP): Info2 [Find] Starting find for miopenConvolutionFwdAlgoGEMM
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmFwd1x1_0_1: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmFwd1x1_0_1_int8: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmFwd1x1_0_2: Not applicable
MIOpen(HIP): Info [FindSolutionImpl] GemmFwdRest (not searchable)
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmFwdRest: Success.
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmBwd1x1_stride1: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmBwd1x1_stride2: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmBwdRest: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmWrw1x1_stride1: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] GemmWrwUniversal: Not applicable
MIOpen(HIP): Info2 [Find] Starting find for miopenConvolutionFwdAlgoFFT
MIOpen(HIP): Info2 [SearchForAllSolutions] fft: Skipped (non-dynamic)
MIOpen(HIP): Info2 [SQLiteBase] Initializing system database file ""
MIOpen(HIP): Info [KernDb] database not present
MIOpen(HIP): Info2 [SQLiteBase] Initializing user database file "C:\\Users\\****\\.miopen\\cache\\3.4.0.15a37b44f\\gfx1030_30.ukdb"
MIOpen(HIP): Info2 [StoreRecord] Trying to store record at key 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F in cache for file "C:\\Users\\****\\.miopen\\db\\gfx1030_30.HIP.3_4_0_c83c11bfb.ufdb.txt"
MIOpen(HIP): Info2 [StoreRecordUnsafe] Storing record: 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 1-4-4-3x3-1-2-2-1-0x0-1x1-1x1-0-NCHW-FP32-F in file "C:\\Users\\****\\.miopen\\db\\gfx1030_30.HIP.3_4_0_c83c11bfb.ufdb.txt"
MIOpen(HIP): Info2 [UpdateDbModificationTime] Updating db modification time for "C:\\Users\\****\\.miopen\\db\\gfx1030_30.HIP.3_4_0_c83c11bfb.ufdb.txt"
MIOpen(HIP): Info2 [ValidateUnsafe] DB file is newer than cache: 87959702400, 87946898200
MIOpen(HIP): Info2 [UpdateDbModificationTime] Updating db modification time for "C:\\Users\\****\\.miopen\\db\\gfx1030_30.HIP.3_4_0_c83c11bfb.ufdb.txt"
MIOpen(HIP): Info2 [Measure] Db::StoreRecord time: 2.4544 ms
MIOpen(HIP): Info2 [default_deallocator] hipFree 144 at 0000000400007000 Ok
MIOpen(HIP): Info2 [default_deallocator] hipFree 64 at 0000000400004000 Ok
MIOpen(HIP): Info2 [default_deallocator] hipFree 36 at 0000000400005000 Ok
MIOpen(HIP): Info2 [default_deallocator] hipFree 16 at 0000000400006000 Ok
MIOpen Error: E:/ML/MIOpen/src/include\miopen/sqlite_db.hpp:252: Cannot open database file:C:\Users\****\.miopen\cache\3.4.0.15a37b44f\gfx1030_30.ukdb
thread '<unnamed>' panicked at zluda_dnn\src\lib.rs:70:16:
[ZLUDA] MIOpen failed: 5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core\src\panicking.rs:223:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7ffc21661fc1 - cudnnConvolutionBackwardData
   1:     0x7ffc2166efba - cudnnConvolutionBackwardData
   2:     0x7ffc216607a7 - cudnnConvolutionBackwardData
   3:     0x7ffc21661e05 - cudnnConvolutionBackwardData
   4:     0x7ffc216633a5 - cudnnConvolutionBackwardData
   5:     0x7ffc21663184 - cudnnConvolutionBackwardData
   6:     0x7ffc21663a33 - cudnnConvolutionBackwardData
   7:     0x7ffc21663882 - cudnnConvolutionBackwardData
   8:     0x7ffc2166270f - cudnnConvolutionBackwardData
   9:     0x7ffc216634be - cudnnConvolutionBackwardData
  10:     0x7ffc21677d25 - cudnnConvolutionBackwardData
  11:     0x7ffc21677dd3 - cudnnConvolutionBackwardData
  12:     0x7ffc21677eb5 - cudnnConvolutionBackwardData
  13:     0x7ffc2165c963 - cudnnBackendFinalize
  14:     0x7ffc2abff730 - _CxxFrameHandler3
  15:     0x7ffc2abf33d8 - is_exception_typeof
  16:     0x7ffc920c3886 - RtlCaptureContext2
  17:     0x7ffc2165c947 - cudnnBackendFinalize
  18:     0x7ffaae1af98c - at::native::cudnn_convolution_transpose
  19:     0x7ffaae1b2e71 - at::native::cudnn_convolution_transpose
  20:     0x7ffaae1bbfa7 - at::native::cudnn_convolution_transpose
  21:     0x7ffaae1c2237 - at::native::cudnn_convolution_transpose
  22:     0x7ffaae1c05bb - at::native::cudnn_convolution_transpose
  23:     0x7ffaae18df3b - at::native::cudnn_convolution_add_relu
  24:     0x7ffaae18c88b - at::native::cudnn_convolution
  25:     0x7ffaafe3e2d4 - at::cuda::where_outf
  26:     0x7ffaafd64cea - at::cuda::bucketize_outf
  27:     0x7ffaff6a8e96 - at::_ops::vsplit_int::redispatch
  28:     0x7ffaff726677 - at::_ops::cudnn_convolution::call
  29:     0x7ffafec48124 - at::native::_convolution
  30:     0x7ffaffb5d0dd - at::compositeexplicitautograd::view_copy_symint_outf
  31:     0x7ffaffb2bcde - at::compositeexplicitautograd::bucketize_outf
  32:     0x7ffaff216214 - at::TensorMaker::make_tensor
  33:     0x7ffaff2bdf8e - at::_ops::_convolution::call
  34:     0x7ffafec473bb - at::native::sym_size
  35:     0x7ffafec5376b - at::native::convolution
  36:     0x7ffaffb5efe3 - at::compositeexplicitautograd::view_copy_symint_outf
  37:     0x7ffaffb2bdef - at::compositeexplicitautograd::bucketize_outf
  38:     0x7ffaff2160b0 - at::TensorMaker::make_tensor
  39:     0x7ffaff29dbec - at::TensorMaker::make_tensor
  40:     0x7ffaff37578c - at::_ops::convolution::redispatch
  41:     0x7ffb00e26774 - torch::autograd::GraphRoot::apply
  42:     0x7ffb00e1cb75 - torch::autograd::GraphRoot::apply
  43:     0x7ffaff2160b0 - at::TensorMaker::make_tensor
  44:     0x7ffaff2ec999 - at::_ops::convolution::call
  45:     0x7ffafec5211d - at::native::conv2d_symint
  46:     0x7ffaffcf1098 - at::compositeimplicitautograd::where
  47:     0x7ffaffcd45b0 - at::compositeimplicitautograd::broadcast_to_symint
  48:     0x7ffaff215e8b - at::TensorMaker::make_tensor
  49:     0x7ffaff833bf7 - at::_ops::conv2d::call
  50:     0x7ffaab2589f9 - THPPointer<_frame>::release
  51:     0x7ffaab2add35 - THPPointer<_frame>::release
  52:     0x7ffc2840140d - cfunction_call
                               at \Objects\methodobject.c:543
  53:     0x7ffc283bc2a8 - _PyObject_MakeTpCall
                               at \Objects\call.c:215
  54:     0x7ffc284d0e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  55:     0x7ffc284d0e02 - call_function
                               at \Python\ceval.c:5893
  56:     0x7ffc284cd14d - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4181
  57:     0x7ffc284cf4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  58:     0x7ffc284cf4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  59:     0x7ffc283bc65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  60:     0x7ffc283be941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  61:     0x7ffc283beaed - method_vectorcall
                               at \Objects\classobject.c:53
  62:     0x7ffc284c8891 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  63:     0x7ffc284d0e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  64:     0x7ffc284d0e02 - call_function
                               at \Python\ceval.c:5893
  65:     0x7ffc284cd14d - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4181
  66:     0x7ffc284cf4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  67:     0x7ffc284cf4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  68:     0x7ffc283bc65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  69:     0x7ffc283be941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  70:     0x7ffc283beb8a - method_vectorcall
                               at \Objects\classobject.c:83
  71:     0x7ffc284d1002 - PyObject_Call
                               at \Objects\call.c:317
  72:     0x7ffc284d1002 - do_call_core
                               at \Python\ceval.c:5945
  73:     0x7ffc284cbf60 - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4277
  74:     0x7ffc284cf4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  75:     0x7ffc284cf4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  76:     0x7ffc283bc65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  77:     0x7ffc283be941 - _PyObject_VectorcallTstate
                               at \Include\cpython\abstract.h:114
  78:     0x7ffc283beb8a - method_vectorcall
                               at \Objects\classobject.c:83
  79:     0x7ffc284d1002 - PyObject_Call
                               at \Objects\call.c:317
  80:     0x7ffc284d1002 - do_call_core
                               at \Python\ceval.c:5945
  81:     0x7ffc284cbf60 - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4277
  82:     0x7ffc284cf4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  83:     0x7ffc284cf4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  84:     0x7ffc283bc65e - _PyFunction_Vectorcall
                               at \Objects\call.c:347
  85:     0x7ffc283bc0b4 - _PyObject_FastCallDictTstate
                               at \Objects\call.c:142
  86:     0x7ffc283bc8d2 - _PyObject_Call_Prepend
                               at \Objects\call.c:431
  87:     0x7ffc2842a0f4 - slot_tp_call
                               at \Objects\typeobject.c:7494
  88:     0x7ffc283bc2a8 - _PyObject_MakeTpCall
                               at \Objects\call.c:215
  89:     0x7ffc284d0e02 - PyObject_Vectorcall
                               at \Include\cpython\abstract.h:123
  90:     0x7ffc284d0e02 - call_function
                               at \Python\ceval.c:5893
  91:     0x7ffc284ccbbd - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:4213
  92:     0x7ffc284cf4df - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:46
  93:     0x7ffc284cf4df - _PyEval_Vector
                               at \Python\ceval.c:5067
  94:     0x7ffc28542661 - PyEval_EvalCode
                               at \Python\ceval.c:1134
  95:     0x7ffc28542661 - run_eval_code_obj
                               at \Python\pythonrun.c:1291
  96:     0x7ffc28542748 - run_mod
                               at \Python\pythonrun.c:1312
  97:     0x7ffc28542348 - pyrun_file
                               at \Python\pythonrun.c:1208
  98:     0x7ffc2854016b - _PyRun_SimpleFileObject
                               at \Python\pythonrun.c:456
  99:     0x7ffc2833baba - _PyRun_AnyFileObject
                               at \Python\pythonrun.c:90
 100:     0x7ffc2833baba - pymain_run_file_obj
                               at \Modules\main.c:357
 101:     0x7ffc2833c731 - pymain_run_file
                               at \Modules\main.c:376
 102:     0x7ffc2833c731 - pymain_run_python
                               at \Modules\main.c:595
 103:     0x7ffc2833d483 - Py_RunMain
                               at \Modules\main.c:674
 104:     0x7ffc2833d483 - pymain_main
                               at \Modules\main.c:1070
 105:     0x7ffc2833d4f6 - Py_Main
                               at \Modules\main.c:1082
 106:     0x7ff7e64f1490 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
 107:     0x7ff7e64f1490 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
 108:     0x7ffc9066e8d7 - BaseThreadInitThunk
 109:     0x7ffc9205bf2c - RtlUserThreadStart
thread caused non-unwinding panic. aborting.
```

**Comment by AngelaCooljx** [comment]
```
(.venv) PS D:\Qwen2.5-VL> python.exe .\test_cuDNN.py
CUDA available on AMD Radeon RX 7800 XT [ZLUDA]
PyTorch Version: 2.4.0+cu118
CUDA Version: 11.8
cuDNN Enabled: True
cuDNN Version: 90100
Input size: torch.Size([1, 1, 4, 4]) → output size: torch.Size([1, 1, 2, 2])
```

Works on mine

**Comment by AngelaCooljx** [comment]
1. The lastest 3.9.0 **nightly** ZLUDA and HIP SDK extension
2. Replaced `cudnn64_9.dll`, `cublas64_11.dll`, `cublasLt64_11.dll`, `cudart64_110.dll`, `cusparse64_11.dll`, `nvrtc64_112_0.dll` and put [`hipblaslt.dll`, `hipblaslt` folder ](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.2.4/hipblaslt-rocmlibs-for-gfx1100-gfx1101-gfx1102-gfx1103-gfx1150-for.hip6.2.7z)in **.venv\Lib\site-packages\torch\lib** 
3. HIP SDK 6.2.0, AMD Software: Adrenalin Edition 25.3.1
4. No another Environment Variable except HIP_PATH,HIP_PATH_62 and bin,lib in system PATH

**Comment by ComradePenguin-1917** [comment]
> 1. The lastest 3.9.0 **nightly** ZLUDA and HIP SDK extension
> 
>     2. Replaced `cudnn64_9.dll`, `cublas64_11.dll`, `cublasLt64_11.dll`, `cudart64_110.dll`, `cusparse64_11.dll`, `nvrtc64_112_0.dll` and put [`hipblaslt.dll`, `hipblaslt` folder ](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.2.4/hipblaslt-rocmlibs-for-gfx1100-gfx1101-gfx1102-gfx1103-gfx1150-for.hip6.2.7z)in **.venv\Lib\site-packages\torch\lib**
> 
>     3. HIP SDK 6.2.0, AMD Software: Adrenalin Edition 25.3.1
> 
>     4. No another Environment Variable except HIP_PATH,HIP_PATH_62 and bin,lib in system PATH

Which bin and lib

**Comment by AngelaCooljx** [comment]
**C:\Program Files\AMD\ROCm\6.2\bin C:\Program Files\AMD\ROCm\6.2\lib**

**Comment by AngelaCooljx** [comment]
```
import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn
import time
import os

# Set environment variables according to ZLUDA documentation (if needed)
os.environ["DISABLE_ADDMM_CUDA_LT"] = "1"

# Fix topk function (if needed)
_topk = torch.topk
def topk(tensor: torch.Tensor, *args, **kwargs):
    device = tensor.device
    values, indices = _topk(tensor.cpu(), *args, **kwargs)
    return torch.return_types.topk((values.to(device), indices.to(device),))
torch.topk = topk

# Create a simple convolutional neural network model
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, padding=1)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(128, 256, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(256 * 4 * 4, 1024)
        self.fc2 = nn.Linear(1024, 10)

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = self.pool(self.relu(self.conv3(x)))
        x = x.view(-1, 256 * 4 * 4)
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

def test_performance(model, input_tensor, title, iterations=10):
    """Test model performance"""
    print(f"\n===== {title} =====")
    
    # Warmup
    for _ in range(3):
        with torch.no_grad():
            _ = model(input_tensor)
    
    # Timing
    torch.cuda.synchronize()
    start_time = time.time()
    
    for _ in range(iterations):
        with torch.no_grad():
            output = model(input_tensor)
            
    torch.cuda.synchronize()
    end_time = time.time()
    
    avg_time = (end_time - start_time) / iterations
    print(f"Average inference time: {avg_time * 1000:.2f} ms")
    print(f"Output shape: {output.shape}")
    return avg_time

def main():
    # Check if CUDA is available
    if not torch.cuda.is_available():
        print("CUDA is not available. Please check your drivers and CUDA installation.")
        return
    
    # Print device information
    device = torch.cuda.current_device()
    print(f"Current device: {torch.cuda.get_device_name(device)}")
    
    # Configure cuDNN
    print("\n===== PyTorch and CUDA Configuration =====")
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA version: {torch.version.cuda}")
    print(f"cuDNN available: {torch.backends.cudnn.is_available()}")
    
    # Create model and input data
    model = SimpleCNN().cuda()
    model.eval()
    batch_size = 32
    input_tensor = torch.randn(batch_size, 3, 32, 32).cuda()
    
    # Test 1: Disable cuDNN
    torch.backends.cudnn.enabled = False
    torch.backends.cuda.enable_flash_sdp(False)
    torch.backends.cuda.enable_math_sdp(True)
    torch.backends.cuda.enable_mem_efficient_sdp(False)
    torch.backends.cuda.enable_cudnn_sdp(False)
    
    no_cudnn_time = test_performance(model, input_tensor, "cuDNN Disabled")
    
    # Test 2: Enable cuDNN (if available)
    if torch.backends.cudnn.is_available():
        torch.backends.cudnn.enabled = True
        torch.backends.cudnn.benchmark = True
        torch.backends.cuda.enable_flash_sdp(False)
        torch.backends.cuda.enable_math_sdp(True)
        torch.backends.cuda.enable_mem_efficient_sdp(False)
        torch.backends.cuda.enable_cudnn_sdp(True)
        
        try:
            cudnn_time = test_performance(model, input_tensor, "cuDNN Enabled")
            print(f"\n===== Performance Comparison =====")
            speedup = no_cudnn_time / cudnn_time
            print(f"cuDNN speedup: {speedup:.2f}x")
            
        except RuntimeError as e:
            print(f"cuDNN test failed: {e}")
            print("Trying with ZLUDA recommended settings...")
            
            # Try with ZLUDA recommended settings
            torch.backends.cudnn.enabled = True
            torch.backends.cuda.enable_flash_sdp(False)
            torch.backends.cuda.enable_math_sdp(True)
            torch.backends.cuda.enable_mem_efficient_sdp(False)
            torch.backends.cuda.enable_cudnn_sdp(True)
            
            try:
                cudnn_time = test_performance(model, input_tensor, "ZLUDA Optimized Settings")
                print(f"\n===== Performance Comparison =====")
                speedup = no_cudnn_time / cudnn_time
                print(f"Optimized speedup: {speedup:.2f}x")
            except RuntimeError as e:
                print(f"ZLUDA optimized settings test failed: {e}")
    else:
        print("\ncuDNN is not available")
    
    # Test basic CUDA operations
    print("\n===== Basic CUDA Operations Test =====")
    try:
        # Test matrix multiplication
        a = torch.randn(1000, 1000).cuda()
        b = torch.randn(1000, 1000).cuda()
        start = time.time()
        c = torch.matmul(a, b)
        torch.cuda.synchronize()
        print(f"Matrix multiplication (1000x1000): {(time.time() - start) * 1000:.2f} ms")
        
        # Test convolution operation
        conv = nn.Conv2d(64, 128, kernel_size=3, padding=1).cuda()
        x = torch.randn(16, 64, 128, 128).cuda()
        start = time.time()
        y = conv(x)
        torch.cuda.synchronize()
        print(f"Convolution operation (16x64x128x128 -> 16x128x128x128): {(time.time() - start) * 1000:.2f} ms")
        
        print("All basic CUDA operations test succeeded!")
    except RuntimeError as e:
        print(f"Basic CUDA operations test failed: {e}")
    
    print("\nTest completed!")

if __name__ == "__main__":
    main()
```
A demo write by Claude 3.7 sonnet. Result below
```
python.exe .\test_cuDNN.py
Current device: AMD Radeon RX 7800 XT [ZLUDA]

===== PyTorch and CUDA Configuration =====
PyTorch version: 2.4.0+cu118
CUDA version: 11.8
cuDNN available: True

===== cuDNN Disabled =====
Average inference time: 4.75 ms
Output shape: torch.Size([32, 10])

===== cuDNN Enabled =====
Average inference time: 0.80 ms
Output shape: torch.Size([32, 10])

===== Performance Comparison =====
cuDNN speedup: 5.94x

===== Basic CUDA Operations Test =====
Matrix multiplication (1000x1000): 1.00 ms
Convolution operation (16x64x128x128 -> 16x128x128x128): 17.00 ms
All basic CUDA operations test succeeded!

Test completed!
```

**Comment by ComradePenguin-1917** [comment]
> 1. The lastest 3.9.0 **nightly** ZLUDA and HIP SDK extension
> 
>     2. Replaced `cudnn64_9.dll`, `cublas64_11.dll`, `cublasLt64_11.dll`, `cudart64_110.dll`, `cusparse64_11.dll`, `nvrtc64_112_0.dll` and put [`hipblaslt.dll`, `hipblaslt` folder ](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.2.4/hipblaslt-rocmlibs-for-gfx1100-gfx1101-gfx1102-gfx1103-gfx1150-for.hip6.2.7z)in **.venv\Lib\site-packages\torch\lib**
> 
>     3. HIP SDK 6.2.0, AMD Software: Adrenalin Edition 25.3.1
> 
>     4. No another Environment Variable except HIP_PATH,HIP_PATH_62 and bin,lib in system PATH

Are these hipblast.dll only for rdna3?If so That may not be compatible with my 6800 :(.

**Comment by cyber827** [comment]
> Please install PyTorch 2.6.0 and copy cudnn.dll over torch/lib/cudnn64_9.dll. Also, set environment variable `DISABLE_ADDMM_CUDA_LT=1`.

Added DISABLE_ADDMM_CUDA_LT=1 in comfyui.bat

I ran the python.exe .\test_cuDNN.py test and it works but I don't see any speed increase in ComfyUI-Zluda

How should the zluda.py be configured?


```
# ------------------- ZLUDA Backend Patch -------------------
if is_zluda:
    print("  ::  ZLUDA detected, disabling non-supported functions.      ")
    torch.backends.cudnn.enabled = False

    if hasattr(torch.backends.cuda, "enable_flash_sdp"):
        torch.backends.cuda.enable_flash_sdp(True)
    if hasattr(torch.backends.cuda, "enable_math_sdp"):
        torch.backends.cuda.enable_math_sdp(False)
    if hasattr(torch.backends.cuda, "enable_mem_efficient_sdp"):
        torch.backends.cuda.enable_mem_efficient_sdp(False)
    print("  ::  CuDNN, flash_sdp, mem_efficient_sdp disabled.           ")
```

Setting  torch.backends.cudnn.enabled = False to True makes it get stuck at 

> Requested to load AutoencodingEngine

**Comment by cyber827** [comment]
Any idea how to implement the changes from 

https://github.com/vladmandic/sdnext/blob/master/modules/zluda.py

https://github.com/vladmandic/sdnext/blob/master/modules/zluda_hijacks.py


Into the https://github.com/patientx/ComfyUI-Zluda fork

https://github.com/patientx/ComfyUI-Zluda/blob/master/comfy/zluda.py
